# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestLectura(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, external_transaction_id: str=None, channel: str=None, peticion: str=None):  # noqa: E501
        """RequestLectura - a model defined in Swagger

        :param external_transaction_id: The external_transaction_id of this RequestLectura.  # noqa: E501
        :type external_transaction_id: str
        :param channel: The channel of this RequestLectura.  # noqa: E501
        :type channel: str
        :param peticion: The peticion of this RequestLectura.  # noqa: E501
        :type peticion: str
        """
        self.swagger_types = {
            'external_transaction_id': str,
            'channel': str,
            'peticion': str
        }

        self.attribute_map = {
            'external_transaction_id': 'externalTransactionId',
            'channel': 'channel',
            'peticion': 'peticion'
        }
        self._external_transaction_id = external_transaction_id
        self._channel = channel
        self._peticion = peticion

    @classmethod
    def from_dict(cls, dikt) -> 'RequestLectura':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestLectura of this RequestLectura.  # noqa: E501
        :rtype: RequestLectura
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestLectura.


        :return: The external_transaction_id of this RequestLectura.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestLectura.


        :param external_transaction_id: The external_transaction_id of this RequestLectura.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestLectura.


        :return: The channel of this RequestLectura.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestLectura.


        :param channel: The channel of this RequestLectura.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def peticion(self) -> str:
        """Gets the peticion of this RequestLectura.


        :return: The peticion of this RequestLectura.
        :rtype: str
        """
        return self._peticion

    @peticion.setter
    def peticion(self, peticion: str):
        """Sets the peticion of this RequestLectura.


        :param peticion: The peticion of this RequestLectura.
        :type peticion: str
        """
        if peticion is None:
            raise ValueError("Invalid value for `peticion`, must not be `None`")  # noqa: E501

        self._peticion = peticion
