# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.request_create_process_proceso import RequestCreateProcessProceso  # noqa: F401,E501
from swagger_server import util


class RequestCreateProcess(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, external_transaction_id: str=None, channel: str=None, proceso: RequestCreateProcessProceso=None):  # noqa: E501
        """RequestCreateProcess - a model defined in Swagger

        :param external_transaction_id: The external_transaction_id of this RequestCreateProcess.  # noqa: E501
        :type external_transaction_id: str
        :param channel: The channel of this RequestCreateProcess.  # noqa: E501
        :type channel: str
        :param proceso: The proceso of this RequestCreateProcess.  # noqa: E501
        :type proceso: RequestCreateProcessProceso
        """
        self.swagger_types = {
            'external_transaction_id': str,
            'channel': str,
            'proceso': RequestCreateProcessProceso
        }

        self.attribute_map = {
            'external_transaction_id': 'externalTransactionId',
            'channel': 'channel',
            'proceso': 'proceso'
        }
        self._external_transaction_id = external_transaction_id
        self._channel = channel
        self._proceso = proceso

    @classmethod
    def from_dict(cls, dikt) -> 'RequestCreateProcess':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestCreateProcess of this RequestCreateProcess.  # noqa: E501
        :rtype: RequestCreateProcess
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestCreateProcess.


        :return: The external_transaction_id of this RequestCreateProcess.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestCreateProcess.


        :param external_transaction_id: The external_transaction_id of this RequestCreateProcess.
        :type external_transaction_id: str
        """
        if external_transaction_id is None:
            raise ValueError("Invalid value for `external_transaction_id`, must not be `None`")  # noqa: E501

        self._external_transaction_id = external_transaction_id

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestCreateProcess.


        :return: The channel of this RequestCreateProcess.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestCreateProcess.


        :param channel: The channel of this RequestCreateProcess.
        :type channel: str
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def proceso(self) -> RequestCreateProcessProceso:
        """Gets the proceso of this RequestCreateProcess.


        :return: The proceso of this RequestCreateProcess.
        :rtype: RequestCreateProcessProceso
        """
        return self._proceso

    @proceso.setter
    def proceso(self, proceso: RequestCreateProcessProceso):
        """Sets the proceso of this RequestCreateProcess.


        :param proceso: The proceso of this RequestCreateProcess.
        :type proceso: RequestCreateProcessProceso
        """
        if proceso is None:
            raise ValueError("Invalid value for `proceso`, must not be `None`")  # noqa: E501

        self._proceso = proceso
