-- 1. Relación entre YTBL_COBRANZAS_BASE_CAMPANIA y YTBL_COBRANZAS_CAMPANIA
ALTER TABLE YTBL_COBRANZAS_BASE_CAMPANIA
ADD CONSTRAINT FK_BASE_CAMPANIA_TO_CAMPANIA
FOREIGN KEY (IDCAMPANIA)
REFERENCES YTBL_COBRANZAS_CAMPANIA(IDCAMPANIA);

-- 2. Relación entre YTBL_COBRANZAS_PROCESO_CAMPANIA y YTBL_COBRANZAS_CAMPANIA
ALTER TABLE YTBL_COBRANZAS_PROCESO_CAMPANIA
ADD CONSTRAINT FK_PROCESO_CAMPANIA_TO_CAMPANIA
FOREIGN KEY (IDCAMPANIA)
REFERENCES YTBL_COBRANZAS_CAMPANIA(IDCAMPANIA);

-- 3. Relación entre YTBL_COBRANZAS_PROCESO_CAMPANIA y YTBL_COBRANZAS_PROCESO
ALTER TABLE YTBL_COBRANZAS_PROCESO_CAMPANIA
ADD CONSTRAINT FK_PROCESO_CAMPANIA_TO_PROCESO
FOREIGN KEY (IDPROCESO)
REFERENCES YTBL_COBRANZAS_PROCESO(IDPROCESO);

-- 4. Relación opcional entre YTBL_BASE_CAMPANIA y YTBL_BASE_COBRANZAS (según IDBASE)
-- Esta relación dependerá de si IDBASE tiene un equivalente en YTBL_BASE_COBRANZAS.
-- Si IDBASE representa una base de cobranzas:
-- ALTER TABLE YTBL_BASE_CAMPANIA
-- ADD CONSTRAINT FK_BASE_CAMPANIA_TO_BASE_COBRANZAS
-- FOREIGN KEY (IDBASE)
-- REFERENCES YTBL_BASE_COBRANZAS(ID);

-- 5. Relación entre YTBL_COBRANZAS_EXCLUSION_CLIENTES y YTBL_COBRANZAS_BASE_COBRANZAS
ALTER TABLE YTBL_COBRANZAS_EXCLUSION_CLIENTES
ADD CONSTRAINT FK_EXCLUSION_TO_BASE_COBRANZAS
FOREIGN KEY (CUENTA)
REFERENCES YTBL_COBRANZAS_BASE_COBRANZAS(CUENTA);

-- 6. Relación opcional entre YTBL_BASE_CAMPANIA y YTBL_PROCESO_CAMPANIA
-- Esto dependerá si hay un flujo lógico entre estas tablas basado en las campañas.
-- ALTER TABLE YTBL_BASE_CAMPANIAO
-- ADD CONSTRAINT FK_BASE_CAMPANIA_TO_PROCESO_CAMPANIA
-- FOREIGN KEY (IDCAMPANIA)
-- REFERENCES YTBL_PROCESO_CAMPANIA(IDCAMPANIA);
