USE BD_CON_COBROS;

CREATE TABLE IF NOT EXISTS YTBL_COBRANZAS_PROCESO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDPROCESO int,
    NOMBRE varchar(100),
	FCREACION date,
	FFINALIZACION date,
	FIPROCESO date,
	FFPROCESO date,
	ISVALID varchar(1)
);

USE BD_CON_COBROS;
DROP TABLE YTBL_COBRANZAS_PROCESO;