USE BD_CON_COBROS;

CREATE TABLE IF NOT EXISTS YTBL_COBRANZAS_PROCESO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDPROCESO int,
    NOMBRE varchar(100),
	FCREACION date,
	FFIN date,
	FINICIO date,
	FECHAFIN date,
	ISVALID varchar(1)
);

DROP TABLE YTBL_COBRANZAS_PROCESO;