USE BD_CON_COBROS;
CREATE TABLE IF NOT EXISTS YTBL_COBRANZAS_CAMPANA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDCAMPANA int,
	NOMBRE varchar(100),
	PORC_DESCUENTO double,
	FCREACION date,
	FFINALIZACION date,
	FICAMPANA date,
	FFCAMPANA date,
	ISVALID varchar(1)
);
SELECT * FROM YTBL_COBRANZAS_CAMPANA;

DELIMITER $$

CREATE TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDCAMPANA
BEFORE INSERT ON YTBL_COBRANZAS_CAMPANA
FOR EACH ROW
BEGIN
    -- Verificar si IDCAMPANIA no fue proporcionado (es NULL)
    IF NEW.IDCAMPANA IS NULL THEN
        -- Asignar a IDCAMPANIA el valor máximo actual + 1, o 1 si no hay registros
        SET NEW.IDCAMPANA = (SELECT IFNULL(MAX(IDCAMPANA), 0) + 1 FROM YTBL_COBRANZAS_CAMPANA);
    END IF;
END$$

DELIMITER ;

DROP TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDCAMPANIA;
DROP TABLE YTBL_COBRANZAS_CAMPANA;