USE BD_CON_COBROS;

CREATE TABLE IF NOT EXISTS YTBL_COBRANZAS_BASE_CAMPANIA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDCAMPANIA int,
	IDBASE int,
	ESTADO varchar(100),
	FCREACION date,
	FFIN date,
	FINICIO date,
	FECHAFIN date,
	ISVALID varchar(1)
);

SELECT * FROM YTBL_BASE_CAMPANIA;
DROP TABLE YTBL_COBRANZAS_BASE_CAMPANIA;