USE BD_CON_COBROS;

CREATE TABLE IF NOT EXISTS YTBL_COBRANZAS_EXCLUSION_CLIENTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE VARCHAR(100) NOT NULL,
    CONTRATO INT NOT NULL,
    CUENTA INT NOT NULL,
    DETALLE VARCHAR(300),
    FECHA_EXCLUSION VARCHAR(75),
    FECHA_CREACION DATE,
    ISVALID VARCHAR(1),
    NAME_FILE VARCHAR(100)
);


DROP TABLE YTBL_COBRANZAS_EXCLUSION_CLIENTES;