USE BD_CON_COBROS;

CREATE TABLE IF NOT EXISTS YTBL_COBRANZAS_PROCESO_CAMPANA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDPROCESO int,
	IDCAMPANA int,
	FCREACION date,
	FFINALIZACION date,
	FINICIO date,
	FECHAFIN date,
	ISVALID varchar(1)
);

SELECT * FROM YTBL_COBRANZAS_PROCESO_CAMPANA;
DROP TABLE YTBL_COBRANZAS_PROCESO_CAMPANA;