USE BD_CON_COBROS;
DELIMITER $$

CREATE TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDCAMPANIA
BEFORE INSERT ON YTBL_COBRANZAS_CAMPANIA
FOR EACH ROW
BEGIN
    -- Verificar si IDCAMPANIA no fue proporcionado (es NULL)
    IF NEW.IDCAMPANIA IS NULL THEN
        -- Asignar a IDCAMPANIA el valor máximo actual + 1, o 1 si no hay registros
        SET NEW.IDCAMPANIA = (SELECT IFNULL(MAX(IDCAMPANIA), 0) + 1 FROM YTBL_COBRANZAS_CAMPANIA);
    END IF;
END$$

DELIMITER ;

DROP TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDCAMPANIA;