USE BD_CON_COBROS;
DELIMITER $$

CREATE TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDCAMPANA
BEFORE INSERT ON YTBL_COBRANZAS_CAMPANA
FOR EACH ROW
BEGIN
    -- Verificar si IDCAMPANIA no fue proporcionado (es NULL)
    IF NEW.IDCAMPANA IS NULL THEN
        -- Asignar a IDCAMPANIA el valor máximo actual + 1, o 1 si no hay registros
        SET NEW.IDCAMPANA = (SELECT IFNULL(MAX(IDCAMPANA), 0) + 1 FROM YTBL_COBRANZAS_CAMPANA);
    END IF;
END$$

DELIMITER ;

DROP TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDCAMPANIA;