USE BD_CON_COBROS;
DELIMITER $$

CREATE TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDPROCESS
BEFORE INSERT ON YTBL_COBRANZAS_PROCESO
FOR EACH ROW
BEGIN
    -- Verificar si IDPROCESO no fue proporcionado (es NULL)
    IF NEW.IDPROCESO IS NULL THEN
        -- Asignar a IDPROCESO el valor máximo actual + 1, o 1 si no hay registros
        SET NEW.IDPROCESO = (SELECT IFNULL(MAX(IDPROCESO), 0) + 1 FROM YTBL_COBRANZAS_PROCESO);
    END IF;
END$$

DELIMITER ;

DROP TRIGGER YTRG_COBRANZAS_AUTOINCREMENT_IDPROCESS;